CREATE TABLE BALANCES (
    ID VARCHAR(36) PRIMARY KEY,
    USER_ID VARCHAR(36) NOT NULL,
    BALANCE INT NOT NULL,
    CURRENCY VARCHAR(10) NOT NULL,
    CONSTRAINT fk_balances_user FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
    CONSTRAINT fk_balances_user_currency UNIQUE (USER_ID, CURRENCY)
);
