CREATE TABLE BALANCES_HISTORY (
    ID VARCHAR(36) PRIMARY KEY,
    TRANSACTION_ID VARCHAR(36) NULL,
    USER_ID VARCHAR(36) NOT NULL,
    BALANCE INT NOT NULL,
    CURRENCY VARCHAR(10) NOT NULL,
    PROOF_IMAGE_URL VARCHAR(255) NOT NULL,
    CREATED_AT BIGINT NOT NULL,
    SOURCE_BANK_ACCOUNT_NUMBER VARCHAR(30) NOT NULL,
    SOURCE_BANK_NAME VARCHAR(30) NOT NULL,
    CONSTRAINT fk_balances_history_user FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
);
