CREATE TABLE USERS (
    ID SERIAL PRIMARY KEY,
    EMAIL VARCHAR NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    PASSWORD TEXT NOT NULL,
    CREATED_AT BIGINT NOT NULL,
    UPDATED_AT BIGINT NOT NULL
);