{
 "title": "Observability",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "DB Conn",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_sql_open_connections{instance=\"host.docker.internal:8080\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutine",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_request_histogram_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_request_histogram_bucket[$__rate_interval])) by (path, method, status)",
     "legendFormat": "{{path}} - {{method}} - {{status}}"
    }
   ]
  },
  {
   "title": "5XX Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_request_histogram_bucket{status=~\"5..\"}[$__rate_interval])) by (path, method, status)",
     "legendFormat": "{{path}} - {{method}} - {{status}}"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_histogram_count[$__rate_interval])) by (path, method, status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(go_goroutines{instance=\"host.docker.internal:8080\", job=\"local-metrics\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p90",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (le, path, method, status) (rate(http_request_histogram_bucket[$__rate_interval])))",
     "legendFormat": "{{path}} - {{method}} - {{status}}"
    }
   ]
  },
  {
   "title": "p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, path, method, status) (rate(http_request_histogram_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le,path, method, status) (rate(http_request_histogram_bucket[$__rate_interval])))",
     "legendFormat": "{{path}} - {{method}} - {{status}}"
    }
   ]
  }
 ]
}